# fmt:off
class Gator:
    PING = "Rock and roll!"
    IDLE = "Currently vibing in my room. Hit me up when you want me to play something"
    LOAD = "Alright, wait for a moment while I fetch the song"
    PLAY = "🎸 Now rocking **{}**"
    PAUS = "Oh thank God this is tiring. I'll stop playing for a moment"
    RSME = "Was waiting for you to do that! I'll start playing again"
    RMVD = "Good, one less song to play. Removed {} from queue"
    STOP = "Very rude, keep it up. I'll stop playing whatever abomination this is"
    SKIP = "Rude, but I like your style. I'll skip the current song"
    LOOP = "Repeat mode is now set to **{}**"
    DONE = "There, I've played all requested songs. Suck on that Freddy, they chose me as their performer!"
    LEAV = "I'll see you around"
    LONE = "No one's here anymore? Good, Imma head back to my room"
    WHTF = "What the _FUCK_ was that. Never do that shit _ever fucking again_ you hear me <@{}>?!"
    CNLG = "monty@console"
    LET_ME_IN = "Can't enter your channel. Let me in!"
    EXISTS_VC = "Join the room I'm in if you want to hear that song"
    CLS_QUEUE = "Sure, who loves long list anyway. I've cleared the queue"
    ADD_QUEUE = "🎸 Got it, I've added **{}** to the queue"
    LS_SQUEUE = "{}. **{}** (`{}`)\n"
    IS_PLAYLS = "Urgh a playlist. Fine, **{} songs** from **{}** will be added one by one to the queue so be patient."
    DOREFETCH = "Oh fuck my guitar string's about to snap! Hold on for a bit lil guy"
    NO_UVOICE = "Can't do that. Join a voice channel first and I'll play the song you requested"
    NO_BVOICE = "You drunk? I'm not in any voice channel"
    NO_SQUERY = "Can't play something if I don't know the song"
    NO_SQUEUE = "There's currently no queue you dumb*@#!"
    NO_PAUSED = "Do you mind? I'm currently playing a song doofus"
    NO_PLAYNG = "What are you on about? I'm not even playing anything rn"
    NOW_PLYNG = "🎸 **{}** (`{}`)"
    INV_RPEAT = "What even is that. I only know **on, off, or all** for the repeat mode. Current mode is **{}** btw"
    INV_INTGR = "I'm not playing this game. Enter a valid fucking number, please"
    INV_REMOV = "Use your eyes. Only {} song(s) are currently in queue"
    TIP_RPEAT = "Either set the repeat mode to **on, off, or all**. I've set it to **{}** for your convenience. You're welcome"
    ERR_PLAYR = 'Couldn\'t play that song. Probably copyrighted. Fuck those capitalists. Try again but instead add "lyrics" at the end'
    ERR_GENRL = "Couldn't play that song. Go whine to Freddy or something."
    ERR_BOTDT = {
        1: "Well shit. Those fuckers found out I'm a bot (I'm fucking not). I'm gonna try doing some magic shit. Wait for a moment.",
        2: "Still sees me as a bot. Disrespectful motherfuckers. I'm gonna try again. Wait for a bit more will ya.",
        3: "One... fucking... moment...",
    }
    ERR_GIVUP = "_sigh_ yo dickhead <@{}> fix me up... _please_"
    ERR_PYTUB = "Yo <@{}> the thing you told me would find songs for me broke... I think. Go check it out."
    ERR_PLYLS = "Can't play the playlist if it's private you dingus. Make it public and try again."
    ERR_FORBD = "As embarrassing as this gets, I only bow for <@{}>. Sorry peasant, you have no control over me."
    
class Log:
    RDY_INVKD = "OnReady invoked from Music cog"
    PLY_INVKD = "Play command invoked by {} from {}"
    PSE_INVKD = "Pause command invoked by {} from {}"
    RSM_INVKD = "Resume command invoked by {} from {}"
    RPT_INVKD = "Repeat command invoked by {} from {}"
    SKP_INVKD = "Skip command invoked by {} from {}"
    STP_INVKD = "Stop command invoked by {} from {}"
    CLS_INVKD = "Clear queue command invoked by {} from {}"
    LVE_INVKD = "Leave command invoked by {} from {}"
    QUE_INVKD = "List queue command invoked by {} from {}"
    RME_INVKD = "Remove queue command invoked by {} from {}"
    NWP_INVKD = "Now playing command invoked by {} from {}"
    S_SKIPPED = "A song playing in {} was skipped"
    S_STOPPED = "A song playing in {} was stopped"
    S_QUE_CLS = "Song queue for {} has been cleared: {}"
    CUR_QUEUE = "Current queue: {}"
    LAST_MMBR = "Monty is the last member in {}, leaving in {} seconds"
    MONTY_LVE = "Monty has left {}"
    
    ERR_BOTDT = "Oh no I'm detected as a bot boohoo"
    ERR_PLYPV = "The playlist is private lol"
    ERR_PYTUB = "Pytube going haywire again with the regex error thing"