# fmt:off
class Gator:
    PING = "Rock and roll!"
    IDLE = "Currently vibing in my room. Hit me up when you want me to play something"
    LOAD = "Alright, wait for a moment while I fetch the song"
    PLAY = "🎸 Now rocking **{}**"
    PAUS = "Paused"
    RSME = "Resumed"
    STOP = "Rude, but I like your style"
    SKIP = "Skipped current song"
    LOOP = "Repeat mode is now set to {}"
    DONE = "I've played all requested songs. How was my performance? Surely I'm better than Freddy, right?"
    LEAV = "I'll see you around"
    LONE = "No one's here anymore? Good, Imma head back to my room"
    LET_ME_IN = "Can't enter your channel. Let me in!"
    EXISTS_VC = "I'll play that song, but I'll be in the room I've currently joined"
    CLS_QUEUE = "Queue cleared"
    ADD_QUEUE = "🎸 Got it, I've add **{}** to the queue"
    NO_UVOICE = "Can't do that. Join a voice channel first and I'll consider your request"
    NO_BVOICE = "Not in a voice channel"
    NO_SQUERY = "Can't play something if I don't know the song. Tell me one!"
    NO_PLAYNG = "No song is playing"
    NO_PAUSED = "No song is paused"
    INV_RPEAT = "What even is that. I only know **on, off, or all** for the repeat mode"
    ERR_PLAYR = 'Couldn\'t play that song. Probably copyrighted. Fuck those capitalists. Try again but instead add "lyrics" at the end'
    ERR_GENRL = "Couldn't play that song. I don't feel so good..."
    
class Log:
    RDY_INVKD = "OnReady invoked from Music cog"
    PLY_INVKD = "Play command invoked by {} from {}"
    SKP_INVKD = "Skip command invoked by {} from {}"
    STP_INVKD = "Stop command invoked by {} from {}"
    CLS_INVKD = "Clear queue command invoked by {} from {}"
    LVE_INVKD = "Leave command invoked by {} from {}"
    QUE_INVKD = "List queue command invoked by {} from {}"
    S_SKIPPED = "A song playing in {} was skipped"
    S_STOPPED = "A song playing in {} was stopped"
    S_QUE_CLS = "Song queue for {} has been cleared: {}"
    CUR_QUEUE = "Current queue: {}"
    LAST_MMBR = "Monty is the last member in {}, leaving in {} seconds"
    MONTY_LVE = "Monty has left {}"